language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - yarn install

script:
  - yarn docs:build

deploy:
  fqdn: aquisitions.spinach-inquisition.org
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  target_branch: gh-pages
  on:
    branch: master